### ISSUE TITLE
Sometimes async processes hang

### ISSUE THREAD

**Issue by smithara** [ESA-VirES/VirES-Server#107]
I have an async process hanging again. It appears to still be running but stuck at 62%
```
{'status': 'STARTED',
   'created': '2019-04-12T03:33:03.481986+00:00',
   'url': 'https://staging.viresdisc.vires.services/wps/67ffaf96-1790-4768-8188-068780ed3f55/executeResponse.xml',
   'started': '2019-04-12T03:33:03.591441+00:00',
   'stopped': None,
   'id': '67ffaf96-1790-4768-8188-068780ed3f55'}
```

It's part of a series of jobs (30 of 37) that I submitted yesterday that each take about 10 minutes to run.

**Comment by pacesm** [comment]
Solved in https://github.com/ESA-VirES/VirES-Server/commit/ca7810d7871d7b2ca8aadc4415eb7c0342eebed9 https://github.com/DAMATS/WPS-Backend/commit/000c6a262054c60ec1ea71bde677c7b1bd34978c
