### ISSUE TITLE
VirES for Swarm - Custom File Format description

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Server#120]
According to the [Custom File Format description](https://github.com/ESA-VirES/VirES-Server/blob/staging/vires/custom_data_format_description.md), The `Radius` variable is not mandatory. However, if the user wants to calculate the residual between the measurement (i.e. `F`, `B_NEC` in the uploaded file) and the model, this variable is necessary. I think it is worth to mention this detail in the format description.

**Comment by pacesm** [comment]
> I think it is worth to mention this detail in the format description.
Fine with me.

TODO: To update the file format description.

**Comment by pacesm** [comment]
@lmar76 Please check the updated [file format description](https://github.com/ESA-VirES/VirES-Server/blob/staging/vires/custom_data_format_description.md).

I have added an extra paragraph in the generic description trying to explain that the radius is required to calculate the models and magnetic coordinates.

Please let me know if you find it sufficient.

FYI, the reason why the radius variable is actually optional is the EEF product which does not contain the radius.

**Comment by lmar76** [comment]
Fine with me

**Comment by pacesm** [comment]
Solved
