### ISSUE TITLE
CDF file upload - missing check for incorrect Timestamp dimension

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/VirES-Server#143]
When a CDF with incorrect array dimension is uploaded the upload fails with an internal server error rather then reporting the actual issue.

```
AttributeError: 'numpy.ndarray' object has no attribute 'tzinfo'
```

**Comment by pacesm** [comment]
FAO @lmar76

**Comment by lmar76** [comment]
Tested with the provided file (SW_TEST_MAGE_LR_1B_20180221T000000_20180221T235959_0201_MDR_MAG_LR.cdf). The error occurs again:

![image](https://user-images.githubusercontent.com/20207042/76198685-ce54dc00-61ee-11ea-9dd1-8c1dc3892859.png)

**Comment by pacesm** [comment]
@lmar76 This is the expected behavior. Before, an Internal Server Error (i.e., a server crash) occurred. Now the server correctly reports an issue with the dimension Timestamp variable.

**Comment by pacesm** [comment]
**Incorrect:**

![image](https://user-images.githubusercontent.com/4050019/76214310-bc823180-620c-11ea-894f-e14cb5f2f48d.png)

**Correct:**
![image](https://user-images.githubusercontent.com/4050019/76214477-1f73c880-620d-11ea-8d98-087a606e2511.png)

**Comment by lmar76** [comment]
Ok, thank you

**Comment by pacesm** [comment]
The fix has been deployed in production.
