### ISSUE TITLE
Server does not accept CDF_REAL8 data type.

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/VirES-Server#144]
CDF files allow double precision float values to be stored either as `CDF_DOUBLE` or `CDF_REAL8` data types. VirES-Server however rejects the CDF files when the `CDF_REAL8` data type is used for mandatory variables although they could be treated the same way as `CDF_DOUBLE`.

FAO @lmar76

**Comment by lmar76** [comment]
Tested with the provided file:

SW_TEST_MAGE_LR_1B_20180221T000000_20180221T235959_0201_MDR_MAG_LR.fixed_dimensions.cdf

The file can be uploaded (no errors are traced) but data can't be visualized:

![image](https://user-images.githubusercontent.com/20207042/76201141-1c6bde80-61f3-11ea-9780-c11b269d6ab3.png)

**Comment by lmar76** [comment]
Tested again, it works.

**Comment by pacesm** [comment]
The fix has been deployed in production.
