### ISSUE TITLE
Malformed timestamps in hapi client response

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Server#176]
Not sure if it is an issue on VirES server or on the HAPI client...

I tried to retrieve MAGA_LR_1B data as indicated in the following notebook cell:

```python
from hapiclient import hapi

HAPISERVER = 'https://testing.vires.services/hapi/'

collection = 'SW_OPER_MAGA_LR_1B'
measurements = [p['name'] for p in hapi(HAPISERVER, collection)['parameters']]
data, meta =  hapi(HAPISERVER, collection, ','.join(measurements), '2021-10-01T00:00:00Z', '2021-10-02T00:00:00Z')
timestamp = [row[0] for row in data]

timestamp[:5]
```

Output is:

```
[b'2021-10-01T00:00:00.000Z',
 b'\x00\x00\x00\x002021-10-01T00:00:01.',
 b'33\xe3?\x00\x00\x00\x002021-10-01T00:00',
 b'433333\xe3?\x00\x00\x00\x002021-10-01T0',
 b'\x01\x00\x00\x00\x9a\x99\x99\x99\x99\x99\xe9\xbf\x00\x00\x00\x002021-10-']
```

**Comment by pacesm** [comment]
Thanks. I confirm there seems to be a problem in the binary serialization of `uint16` flags (`Flags_Platform`, `ASM_Freq_Dev`, and `SyncStatus`). 

The rest of the parameters seems to be okay. Try
```python
measurements = [p['name'] for p in hapi(HAPISERVER, collection)['parameters'] if p['x_type'] != 'uint16']
```

This should be easy to fix.

**Comment by pacesm** [comment]
The problem turned out to be an incorrect data type of the `ASM_Freq_Dev` in the product type configuration. It should be fixed now. 

For more details see https://github.com/ESA-VirES/VirES-Server/commit/ec577c1b2f46c95c57462eb064bbfb1fceb70da7.

**Comment by lmar76** [comment]
It works. Thank you
