### ISSUE TITLE
HAPI error while retrieving 1 day MAG HR data

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Server#177]
I tried to retrieve 1 day of `SW_OPER_MAGA_HR_1B` data:

```python
HAPISERVER = 'https://testing.vires.services/hapi/'

collection = 'SW_OPER_MAGA_HR_1B'
measurements = [p['name'] for p in hapi(HAPISERVER, collection)['parameters']]
data, meta = hapi(HAPISERVER, collection, ','.join(measurements), '2017-11-25T00:00:00', '2017-11-26T00:00:00')
```

and the following exception was raised:
```
HAPIError: Bad request - too much time or data requested
```

Please note that the same data and time interval can be downloaded using `viresclient`.

**Comment by pacesm** [comment]
FYI, currently, the synchronous HAPI responses have same limit as the *synchronous* API downloads 432,000 samples which is equivalent to 5 days of the 1Hz `MAGx_LR_1B` data or 2 h and 24 min of 50Hz `MAGx_HR_1B` data.

Note that by default the VirES Python client uses the *asynchronous* API downloads which have the limit 10x larger 4,320,000 samples which is equivalent to 50 days of the 1Hz `MAGx_LR_1B` data or 1 day of 50Hz `MAGx_HR_1B` data.

Note that in case of the streamed HAPI response the number of samples is guessed from the nominal data cadence while the the VirES API does the proper sample counting. I.e., in case of an irregularly sampled dataset the number of samples returned by HAPI might slightly exceed the actual limit.

Do you think the limit is too short? I'm currently not in favor of increasing the limit. The performance of the HAPI data serialization is still sub-optimal, IMO.

If you need a larger time-span you might consider splitting the HAPI request into smaller chunks:
```
>> help(hapi)
hapi(*args, **kwargs)
    ...   
    Parameters
    ----------
    ...
    options : dict
    ...
            `parallel` (False) If true, make up to `n_parallel` requests to
                server in parallel (uses threads)
    
            `n_parallel` (5) Maximum number of parallel requests to server.
                Max allowed is 5.
    
            `n_chunks` (None) Get data by making `n_chunks` requests by splitting
                requested time range. `dt_chunk` is ignored if `n_chunks` is
                not `None`. Allowed values are integers > 1.
    
            `dt_chunk` ('infer') For requests that span a time range larger
                than the default chunk size for a given dataset cadence, the
                client will split request into chunks if `dt_chunk` is not
                `None`.
    
                Allowed values of `dt_chunk` are 'infer', `None`, and an ISO 8601
                duration that is unambiguous (durations that include Y and M are not
                allowed). The default chunk size is determined based on the cadence
                of the dataset requested according to
    
                    cadence < PT1S              dt_chunk='PT1H'
                    PT1S <= cadence <= PT1H     dt_chunk='P1D'
                    cadence > PT1H              dt_chunk='P30D'
                    cadence >= P1D              dt_chunk='P365D'
    
                If the dataset does not have a cadence listed in its metadata, an
                attempt is made to infer the cadence by requesting a small time range
                of data and doubling the time range until 10 records are in the response.
                The cadence used to determine the chunk size is then the average time
                difference between records.
    
                If requested time range is < 1/2 of chunk size, only one request is
                made. Otherwise, start and/or stop are modified to be at hour, day,
                month or year boundaries and requests are made for a time span of a
                full chunk, and trimming is performed. For example,
    
                    Cadence = PT1M and request for
                        start/stop=1999-11-12T00:10:00/stop=1999-11-12T12:09:00
                        Chunk size is P1D and requested time range < 1/2 of this
                        =>  Default behavior
                    Cadence = PT1M and request for
                        start/stop=1999-11-12T00:10:00/1999-11-12T12:10:00
                        Chunk size is P1D and requested time range >= 1/2 of this
                        =>  One request with start/stop=1999-11-12/1999-11-13
                            and trim performed
                    Cadence = PT1M and request for
                        start/stop=1999-11-12T00:10:00/1999-11-13T12:09:00
                        Chunk size is P1D and requested time range > than this
                        =>  Two requests:
                            (1) start/stop=1999-11-12/start=1999-11-13
                            (2) start/stop=1999-11-13/start=1999-11-14
                            and trim performed
```

**Comment by lmar76** [comment]
Thank you for the information. As you explained, if we download data via `viresclient` using the *synchronous* API we have the same limitation of the HAPI client. So, as far as the two clients are aligned, in terms of download capabilities (even if, as far as I understood,HAPI client uses only the synchronous API), I think it's fine.

IMHO It might be worth to write some information on the *synchronous/asynchronous* type of request and the implied limits in terms of samples and time span.

**Comment by pacesm** [comment]
> IMHO It might be worth to write some information on the synchronous/asynchronous type of request and the implied limits in terms of samples and time span.

That is a good point. We should mention this on the HAPI landing page (covered by https://github.com/ESA-VirES/VirES-Server/issues/178)

AFAIK, the VirES Python client chops larger time selections into small chunks transparently.
