### ISSUE TITLE
Error in SW_OPER_TECxTMS_2F

### ISSUE THREAD

**Issue by smithara** [ESA-VirES/VirES-Server#201]
Within the `SW_OPER_TECxTMS_2F` collections I get an error when trying to retrieve `DCB` or `DCB_Error`:
```
WPS Request Failed! Reason: NoApplicableCode: 'float' object has no attribute 'shape'
```

**Comment by pacesm** [comment]
Ok, I'll check it.

**Comment by pacesm** [comment]
Patched the server. Should be fixed. Please check.

**Comment by smithara** [comment]
Looks good now thank you!
