### ISSUE TITLE
Misordered latitude/longitude in GetObservatories process

### ISSUE THREAD

**Issue by smithara** [ESA-VirES/VirES-Server#237]
The generated CSV from the GetObservatories process has the latitude and longitude switched. Seems to be here: https://github.com/ESA-VirES/VirES-Server/blob/a022366de4d59ff572adda0af53491dae35c01e2/vires/vires/processes/get_observatories.py#L167

---

![image](https://github.com/user-attachments/assets/b5643e28-cad7-4312-bc8e-ea2b240c0ed3)

**Comment by pacesm** [comment]
Yep, this looks like an error. I'll take care of it.

**Comment by pacesm** [comment]
Fixed and deployed in production. Please check.

**Comment by smithara** [comment]
Yes looks good now, thanks!
