### ISSUE TITLE
The dimensions #0 of 'time' X does not match the required value Y!

### ISSUE THREAD

**Issue by pacesm** [ESA-VirES/VirES-Server#25]
Certain combination of filters produces following download error:
```
The dimensions #0 of 'time' X does not match the required value Y!
```

**Comment by santilland** [comment]
As far as i can see it is just a combination of any of the parameters (of the product or indices) with additionally calculated parameters (mlt and qdlat). 
mlt and qdlat work also fine if not combined with others
