### ISSUE TITLE
Introduce binary (or compressed) protocol

### ISSUE THREAD

**Issue by Schpidi** [ESA-VirES/VirES-Server#6]
For transfer of Swarm Data between server and client.

**Comment by Schpidi** [comment]
See also ESA-VirES/WebClient-Framework#16

**Comment by pacesm** [comment]
Little update on this issue ...
I think we do not need a new protocol and we can live with the HTTP/WPS. We however need a better transfer data format.

I made a couple of benchmarks to asses the response generation performance and to get some figures for different factors  contributing to the relatively large response times.
The benchmark were run on the `staging/testing` VM with a real SWARM product (LR with 86400 samples).

This table displays effect of the source file compression and OS disc cache:

|  action | time / s |
|:---|:---:|
|  CDF file read (compressed, cached) | 0.20 |
|  CDF file read (uncompressed copy, cached) | 0.02 |
|  CDF file read (compressed, non-cached)  | 2.50 |
 
This table shows the time contribution of the in-memory data conversions to the response time and size of the response (the size of the source data is listed as a reference):

|  action | time / s | output size / MiB |
|:---|:---:|:---:|
| source data (compressed) | -- | 10.3 | 
| CDF (uncompressed) | 0.03 | 21.7 |
| CSV (original implementation, ISO time) | **14.6** | 30.0 |
| CSV (original implementation, Unix epoch) | 13.6 | 29.8  |
| CSV (new implementation, ISO time) | 11.0 | 25.6  |
| CSV (new implementation, Unix epoch) | **10.0** | 24.8  |

The `gzip` compression of the uncompressed binary CDF takes ~1s while compression of the CSV data takes ~2.2s. The output size is slightly larger for CDF, 10MiB, compared to 9MiB for CSV.

From there figures following conclusions can be made:
* The size of the well prepared CSV does not differ to much from the uncompressed binary file.
* The transport `gzip` compression makes sense (only) for slower connections (say < 10MiB/s). [unless we plan to access the service via a 100Mbit/s line the compression overhead is compensated by the saved transport time]
* The conversion of binary data to strings is however quite significant and it is dominating the response rendering time (some overhead can be expected also on the client side). [we need a binary data format]
* For large filtered periods the response time might be dominated by data reading (1year ~4GiB of cached data will require min. 73s; 1year of un-cached data will require min. 15min.) [we need asynchronous data rendering for the download]

**Comment by pacesm** [comment]
solved by use of `msgpack`
