### ISSUE TITLE
Issue when selecting time interval with two products where second product has data gap

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/VirES-Server#63]
For examples when selecting MAG and EFI data from "2016-03-03T08:30:09.101Z" to "2016-03-03T14:36:07.278Z" we get:
<ows:ExceptionText>zero-size array to reduction operation minimum which has no identity</ows:ExceptionText>
because during that period there is no EFI data, but there is an EFI daily product available.

**Comment by pacesm** [comment]
Should be fixed by https://github.com/ESA-VirES/VirES-Server/pull/70
Please check if it is really so and close the ticket.
