### ISSUE TITLE
EEF data always return nan when combining it with another product using gap aware algorithm

### ISSUE THREAD

**Issue by santilland** [ESA-VirES/VirES-Server#64]
Before the gap aware algorithm it returned interpolated points for every value of the master product (also not wanted).
The expected behavior now would be to see some values for EEF when combined with another product (e.g. MAG or EFI) but only "nan" is returned for all values.

**Comment by pacesm** [comment]
daa222c8c5fddf841af091eda08c241ec14db866 tries to solve the issue.
The updated interpolation will match the EEF sample if the master sample is close to the EEF value (right now set +/- 0.5s).

This works if no filter is applied. Any filter (including the temporal sub-sampling) may remove the sample containing the single EEF values though.

**Comment by pacesm** [comment]
This one should be fixed. Please check if it is really so and close the ticket.

**Comment by pacesm** [comment]
Fixed in https://github.com/ESA-VirES/VirES-Server/pull/70/commits/daa222c8c5fddf841af091eda08c241ec14db866
Merged in PR https://github.com/ESA-VirES/VirES-Server/pull/70
