### ISSUE TITLE
harmonize timestaps used 

### ISSUE THREAD

**Issue by eox-cs1** [ESA-VirES/VirES-Server#67]
Ensure that all timestamps used eg. in log-files, DB-entires, etc. are in the same time-zone (preferably UTC). It is rather confusing to always consider time-zome or daylight-savings-time when searching/comparing log- or DB entries for certain occurrances.

**Comment by pacesm** [comment]
Time zone of the logging time-stamps is not controlled by the SW (VirES-Server) but by the logging configuration (set in [VirES](https://github.com/ESA-VirES/VirES) repo).

As far as the DB time-stamps are considered, VirES-Server/EOxServer/Django instance is already configured to use the UTC as the default time-zome (i.e., all automatic DB time-stamps are already in UTC). Futher, all the DB time-stamps inserted by the Python code of this repository are strictly using UTC time-zone.

There is nothing to be done in this repository. If you still encounter non-UTC time-stamps in the DB please note that these may come from third-party Django Apps. In such a case I recommend to stick to the best practise of setting the local time to UTC on the production machines.
