### ISSUE TITLE
change interp1d for InterpolatedUnivariateSpline?

### ISSUE THREAD

**Issue by miktoki** [ESA-VirES/VirES-Server#8]
I am not sure of how central interpolation is to your implementation, but based on personal experience 
[`InterpolatedUnivariateSpline`](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.interpolate.InterpolatedUnivariateSpline.html) seems to outperform `interp1d`. As they both are in `scipy.interpolate` I think it would be worth investigating if it is an improvement.

**Comment by pacesm** [comment]
@miktoki Thanks for the tip.

I'll try to compare them and if the spline interpolation gives better results then we can replace the `interp1d`.

**Comment by pacesm** [comment]
an update ...
I checked the [`InterpolatedUnivariateSpline`](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.interpolate.InterpolatedUnivariateSpline.html) and it has following issues:
1. compared to `interp1d` it does not seem to support the `nearest` (0 order) interpolation which is used for the Kp index.
2. compared to `interp1d` it does not support custom fill-value (e.g., `NaN`) outside of the interpolated interval.

**Comment by pacesm** [comment]
the performance of the currently used interpolation method is sufficiently
